config/routes.rb
Preflight::Engine.routes.draw do
  get '/auth/:provider/callback' => 'sessions#create'
  post '/auth/:provider/callback' => 'sessions#create'

  resources :r,
    only: :show,
    controller: :referrals,
    as: :referral


  resource :admin, only: :show, controller: 'admins' do
    resources :campaigns, controller: 'admin/campaigns' do
      resources :rewards, controller: 'admin/rewards', only: [:new, :create]
    end
  end

  resources :subscribers, only: [:new, :create]

  resources :campaigns, only: [] do
    resources :subscribers, only: [:new, :create]
  end

  resource :sharing_center
  resources :shares, only: :create

  root 'subscribers#new'
end

app/models/preflight/campaign.rb
module Preflight
  class Campaign < ActiveRecord::Base
    is_sluggable :title, history: false

    has_many :rewards,
      -> { order(:rank) },
      class_name: 'Preflight::Reward',
      foreign_key: 'campaign_id',
      dependent: :destroy

    include BetterDatePicker::Model

    better_date_picker :started_at
    better_date_picker :ended_at

    validates :title, uniqueness: true, presence: true
    validates :started_at, presence: true
    validate :started_at_before_ended_at

    def started_at_before_ended_at
      if started_at.present? && ended_at.present?
        if ended_at < started_at
          errors.add(:ended_at, 'must be after the start')
        end
      end
    end

    class << self
      def active
        where('started_at <= :now AND (ended_at >= :now OR ended_at IS NULL)',
          now: Time.now)
      end
    end
  end
end

app/controllers/preflight/admin/campaigns_controller.rb
module Preflight
  module Admin
    class CampaignsController < AdminController
      respond_to :html

      def new
        @campaign = Campaign.new
      end

      def create
        @campaign = Campaign.new(campaign_params)
        @campaign.save
        respond_with(@campaign, location: admin_campaigns_path)
      end

      def index
        @campaigns = Campaign.page(params[:page])
      end

      def show
        @campaign = Campaign.find_using_slug!(params[:id])
      end

      protected
      def campaign_params
        params.require(:campaign).permit(:title, :description, :ended_at_date,
          :started_at_date)
      end
    end
  end
end

app/views/preflight/admin/campaigns/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Campaigns</h1>
    <%= new_link_to 'Add a new campaign', new_admin_campaign_path %>

    <%- if @campaigns.present? -%>
      <table>
        <thead>
          <tr>
            <th>Campaign Name</th>
            <th>Start</th>
            <th>End</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%- @campaigns.each do |campaign| %>
            <tr>
              <td><%= link_to campaign.title, admin_campaign_path(campaign) %></td>
              <td><%= campaign.started_at %></td>
              <td><%= campaign.ended_at %></td>
              <td><%= link_to 'Show', admin_campaign_path(campaign) %></td>
            </tr>
          <%- end -%>
        </tbody>
      </table>
    <%- end -%>
  </div>
</div>

app/views/preflight/admin/campaigns/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Add a new campaign</h1>

    <%= preflight_form_for [:admin, @campaign] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :started_at_date %>
      <%= f.input :ended_at_date %>

      <%= f.button :submit %>
    <% end %>
  </div>
</div>

<%= content_for :extra_footer do %>
  <script type="text/javascript">
    $(function(){
      new Preflight.Views.Campaigns.Form('#new_campaign');
    });
  </script>
<%- end -%>

app/views/preflight/admin/campaigns/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <ul class="breadcrumbs">
      <li><%= link_to 'Home', admin_path %></li>
      <li><%= link_to 'Campaigns', admin_campaigns_path %></li>
      <li class="current"><%= @campaign.title %></li>
    </ul>
    <h1><%= @campaign.title %></h1>

  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <h3>Rewards</h3>

    <%= new_link_to 'New Reward', new_admin_campaign_reward_path(@campaign) %>

    <%- if @campaign.rewards.present? -%>
      <table>
        <thead>
          <th>Title</th>
          <th>Threshold Type</th>
          <th>Threshold Units</th>
        </thead>

        <tbody>
          <%- @campaign.rewards.each do |reward| -%>
            <tr>
              <td><%= reward.title %></td>
              <td><%= reward.threshold_type %></td>
              <td><%= reward.threshold_units %></td>
            </tr>
          <%- end -%>
        </tbody>
      </table>
    <%-end -%>
  </div>
</div>