config/routes.rb
Preflight::Engine.routes.draw do
  get '/auth/:provider/callback' => 'sessions#create'
  post '/auth/:provider/callback' => 'sessions#create'

  resources :r,
    only: :show,
    controller: :referrals,
    as: :referral


  resource :admin, only: :show, controller: 'admins' do
    resources :campaigns, controller: 'admin/campaigns' do
      resources :rewards, controller: 'admin/rewards', only: [:new, :create]
    end
  end

  resources :subscribers, only: [:new, :create]

  resources :campaigns, only: [] do
    resources :subscribers, only: [:new, :create]
  end

  resource :sharing_center
  resources :shares, only: :create

  root 'subscribers#new'
end

app/models/preflight/reward.rb
module Preflight
  class Reward < ActiveRecord::Base
    THRESHOLD_TYPES = [
      'campaign_subscription',
      'share'
    ]

    belongs_to :campaign,
      class_name: 'Preflight::Campaign',
      foreign_key: 'campaign_id'

    validates :title, presence: true
    validates :description, presence: true

    validates :campaign, presence: true

    validates :threshold_type,
      inclusion: THRESHOLD_TYPES,
      presence: true

    validates :threshold_units,
      numericality: {
        only_integer: true,
        greater_than: 0
      }

    validates :rank,
      presence: true,
      numericality: {
        only_integer: true,
        greater_than: 0
      },
      uniqueness: {
        scope: :campaign_id
      }
  end
end

app/controllers/preflight/admin/rewards_controller.rb
module Preflight
  module Admin
    class RewardsController < AdminController
      respond_to :html

      def new
        campaign
        @reward = campaign.rewards.new
      end

      def create
        @reward = campaign.rewards.build
        @reward.attributes = reward_params
        @reward.threshold_type = 'campaign_subscription'
        @reward.save
        respond_with(@reward, location: admin_campaign_path(campaign))
      end

      protected
      def campaign
        @campaign ||= Preflight::Campaign.find_using_slug!(params[:campaign_id])
      end

      def reward_params
        params.require(:reward).permit(:title, :description, :threshold_units,
          :rank)
      end
    end
  end
end

app/views/preflight/admin/rewards/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <ul class="breadcrumbs">
      <li><%= link_to 'Home', admin_path %></li>
      <li><%= link_to 'Campaigns', admin_campaigns_path %></li>
      <li><%= link_to @campaign.title, admin_campaign_path(@campaign) %></li>
      <li class="current">New Reward</li>
    </ul>

    <h1>Create a reward for <%= @campaign.title %></h1>

    <%= simple_form_for [:admin, @campaign, @reward] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :threshold_units %>
      <%= f.input :rank %>

      <%= f.button :submit %>
    <%- end %>
  </div>
</div>